apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ns.name" . }}-config
  labels: {{- include "ns.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ns.name" . }}-secrets
  labels: {{- include "ns.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
