import { redis } from '../shared/redis';
import { logger } from '../shared/logger';

/**
 * Phase 25 — admin live-events emitter (dashboard invalidation hints).
 *
 * HINT DOCTRINE (locked, D2/D10) — read before adding an emit point or a type:
 *   "the socket is a hint, Postgres is the truth."
 *   - The wire carries INVALIDATION HINTS, never row DATA. Every envelope is
 *     `{ type, id?, at }`: a type and, at most, an opaque row id scoped to the
 *     caller's own tenant. The dashboard turns a hint into ONE react-query
 *     refetch through the unchanged REST API. NEVER put row contents (message
 *     text, names, statuses, counts) on this channel — a hint may leak at most
 *     row EXISTENCE within one's own tenant, and nothing more.
 *   - The channel name is derived server-side from the tenant/env id
 *     (`tenantEventsChannel`); a client never chooses it. Cross-tenant
 *     isolation is enforced in the gateway (it subscribes the socket only to
 *     the channel of the VERIFIED env). This function trusts its caller's
 *     tenantId — always pass the tenant that owns the row you just wrote.
 *   - `queue.depths` is the ONE data-carrying event, and it does NOT flow
 *     through this function: it is generated by the gateway itself (an infra
 *     gauge, not tenant rows). Do not emit it here.
 */
export type TenantEventType =
  | 'conversation.changed'
  | 'approval.changed'
  | 'eval.finished'
  | 'knowledge.changed'
  | 'message.changed'
  | 'connection.changed'
  | 'memory.changed'
  | 'queue.deadletter';

/** Redis pub/sub channel carrying one tenant's admin hint stream. */
export function tenantEventsChannel(tenantId: string): string {
  return 'tenant-events:' + tenantId;
}

/**
 * Publish a tenant-scoped admin invalidation hint. Envelope: `{ type, id?, at }`
 * (ISO `at`). Call it with `void` — this is FIRE-AND-FORGET and NEVER throws: a
 * Redis blip must never fail the write path this rides on. On publish failure
 * the hint is dropped (a reconnecting dashboard re-syncs via its catch-up
 * refetch sweep, so a lost hint costs nothing) and a warning is logged.
 */
export function emitTenantEvent(
  tenantId: string,
  type: TenantEventType,
  id?: string,
): Promise<void> {
  const envelope = JSON.stringify({
    type,
    ...(id !== undefined ? { id } : {}),
    at: new Date().toISOString(),
  });
  return redis
    .publish(tenantEventsChannel(tenantId), envelope)
    .then(() => undefined)
    .catch((err) => {
      logger.warn({ err, tenantId, type }, 'emitTenantEvent publish failed — hint dropped');
    });
}
