/**
 * Phase 25 slice D — the dashboard's admin-event invalidation table.
 *
 * The table is the single mapping from a hint type to the react-query keys that
 * a hint invalidates. The dashboard already enforces exhaustiveness at COMPILE
 * time (`Record<TenantEventType, …>` fails to typecheck if a union member is
 * unmapped); this suite is the RUNTIME tripwire: every hint type must resolve to
 * at least one query-key prefix, `queue.depths` (the data-carrying infra gauge)
 * must never appear in the table, and the type set must stay in lockstep with
 * the server-side frozen union in src/core/tenant-events.ts.
 *
 * The dashboard module imports cleanly into vitest (react resolves at the repo
 * root, react-query from dashboard/node_modules), so the REAL table is tested —
 * no local replica.
 */
import { describe, expect, test } from 'vitest';
import {
  INVALIDATION_TABLE,
  TENANT_EVENT_TYPES,
  type TenantEventType,
} from '../../dashboard/src/lib/adminEvents';

// Mirrors the frozen union in src/core/tenant-events.ts (TenantEventType) MINUS
// `queue.depths`, which never rides emitTenantEvent (it is generated by the
// gateway and written straight into the cache, never through this table). If the
// server union changes, this list must change with it — that is the drift alarm.
const EXPECTED_TYPES: TenantEventType[] = [
  'conversation.changed',
  'approval.changed',
  'eval.finished',
  'knowledge.changed',
  'message.changed',
  'connection.changed',
  'memory.changed',
  'queue.deadletter',
];

describe('admin-events invalidation table', () => {
  test('every TenantEventType maps to at least one query-key prefix', () => {
    for (const type of TENANT_EVENT_TYPES) {
      const keys = INVALIDATION_TABLE[type](); // no id → list-level prefixes
      expect(Array.isArray(keys), `${type} must map to an array`).toBe(true);
      expect(keys.length, `${type} must map to >= 1 query key`).toBeGreaterThanOrEqual(1);
      // Each prefix is a non-empty tuple (a react-query key STARTS-WITH prefix).
      for (const prefix of keys) {
        expect(Array.isArray(prefix)).toBe(true);
        expect(prefix.length).toBeGreaterThanOrEqual(1);
      }
    }
  });

  test('id-bearing types still yield >= 1 key when an id is supplied', () => {
    for (const type of TENANT_EVENT_TYPES) {
      expect(INVALIDATION_TABLE[type]('some-row-id').length).toBeGreaterThanOrEqual(1);
    }
  });

  test('queue.depths is NOT in the table (data-carrying gauge, handled out-of-band)', () => {
    expect('queue.depths' in INVALIDATION_TABLE).toBe(false);
    expect(TENANT_EVENT_TYPES).not.toContain('queue.depths' as TenantEventType);
  });

  test('the table type set stays in lockstep with the server union (drift alarm)', () => {
    expect([...TENANT_EVENT_TYPES].sort()).toEqual([...EXPECTED_TYPES].sort());
    // TENANT_EVENT_TYPES is exactly the table's own keys.
    expect([...TENANT_EVENT_TYPES].sort()).toEqual(Object.keys(INVALIDATION_TABLE).sort());
  });
});
